//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_trail
    {
        public int Audit_Trail_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<System.DateTime> Trail_DateTime { get; set; }
        public string Trail_Description { get; set; }
        public string Deleted_Record { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
