//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_instance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booking_instance()
        {
            this.tasks_completed = new HashSet<tasks_completed>();
        }
    
        public int Booking_Instance_ID { get; set; }
        public string Instance_Comments { get; set; }
        public Nullable<System.TimeSpan> Instance_Start_Time { get; set; }
        public Nullable<System.TimeSpan> Instance_End_Time { get; set; }
        public Nullable<int> Booking_ID { get; set; }
        public Nullable<int> Quote_ID { get; set; }
        public Nullable<int> Address_ID { get; set; }
    
        public virtual address address { get; set; }
        public virtual booking booking { get; set; }
        public virtual quote quote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tasks_completed> tasks_completed { get; set; }
    }
}
