//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_reminders
    {
        public int Booking_ID { get; set; }
        public int Reminder_ID { get; set; }
        public string Reminder_Description { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual reminder reminder { get; set; }
    }
}
