//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class client_contact_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client_contact_type()
        {
            this.client_contact = new HashSet<client_contact>();
        }
    
        public int Client_Contact_Type_ID { get; set; }

        [Required]
        [Display(Name = "Client Contact Type Name")]
        [StringLength(50)]
        public string Type_Name { get; set; }

        [Required]
        [Display(Name = "Client Contact Type Description")]
        [StringLength(255)]

        public string Type_Description { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_contact> client_contact { get; set; }
    }
}
