//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee_milestone
    {
        [Display(Name = "Employee Name")]
        public int Employee_ID { get; set; }

        [Display(Name = "Milestone Name")]
        public int Milestone_ID { get; set; }

        [Required]
        [Display(Name = "Reason for Milestone")]
        [StringLength(255)]
        public string Reason_Milestone { get; set; }

        [Required]
        [Display(Name = "Milestone Progress")]
        [Range(0, 1000, ErrorMessage = "Please enter a number that is above 0 but below 1000")]
        public Nullable<int> Milestone_Progress { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual milestone milestone { get; set; }
    }
}
