//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class instructor_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public instructor_type()
        {
            this.instructors = new HashSet<instructor>();
        }
    
        public int Instructor_Type_ID { get; set; }

        [Required]
        [Display(Name = "Instructor Type Name")]
        [StringLength(50)]
        public string Instructor_Type_Name { get; set; }

        [Required]
        [Display(Name = "Instrutor Type Description")]
        [StringLength(255)]
        public string Instrutor_Type_Description { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instructor> instructors { get; set; }
    }
}
