//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class marketing
    {
        public int Marketing_ID { get; set; }
        public string Marketing_Description { get; set; }
        public byte[] Marketing_Image { get; set; }
        public Nullable<int> Marketing_Type_ID { get; set; }
        public Nullable<int> Mailing_List_ID { get; set; }
    
        public virtual mailing_list mailing_list { get; set; }
        public virtual marketing_type marketing_type { get; set; }
    }
}
