//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quote()
        {
            this.booking_instance = new HashSet<booking_instance>();
        }
    
        public int Quote_ID { get; set; }
        public string Quote_Name { get; set; }
        public string Quote_Ref_Num { get; set; }
        public Nullable<System.DateTime> Quote_Date { get; set; }
        public string Quote_Price { get; set; }
        public Nullable<int> Quote_Status_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking_instance> booking_instance { get; set; }
        public virtual quote_status quote_status { get; set; }
    }
}
