//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class reminder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reminder()
        {
            this.booking_reminders = new HashSet<booking_reminders>();
        }
    
        public int Reminder_ID { get; set; }
        public Nullable<int> Reminder_Type_ID { get; set; }
        public Nullable<System.DateTime> Reminder_DateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking_reminders> booking_reminders { get; set; }
        public virtual reminder_type reminder_type { get; set; }
    }
}
