//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<access_level> access_level { get; set; }
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<audit_trail> audit_trail { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<booking_instance> booking_instance { get; set; }
        public virtual DbSet<booking_reminders> booking_reminders { get; set; }
        public virtual DbSet<booking_type> booking_type { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<client_contact> client_contact { get; set; }
        public virtual DbSet<client_contact_type> client_contact_type { get; set; }
        public virtual DbSet<client_mailinglist> client_mailinglist { get; set; }
        public virtual DbSet<client_rating> client_rating { get; set; }
        public virtual DbSet<client_type> client_type { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employee_client> employee_client { get; set; }
        public virtual DbSet<employee_mailinglist> employee_mailinglist { get; set; }
        public virtual DbSet<employee_milestone> employee_milestone { get; set; }
        public virtual DbSet<employee_type> employee_type { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<instructor> instructors { get; set; }
        public virtual DbSet<instructor_type> instructor_type { get; set; }
        public virtual DbSet<mailing_list> mailing_list { get; set; }
        public virtual DbSet<marketing> marketings { get; set; }
        public virtual DbSet<marketing_type> marketing_type { get; set; }
        public virtual DbSet<milestone> milestones { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<quote> quotes { get; set; }
        public virtual DbSet<quote_status> quote_status { get; set; }
        public virtual DbSet<registration_token> registration_token { get; set; }
        public virtual DbSet<reminder> reminders { get; set; }
        public virtual DbSet<reminder_type> reminder_type { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<task_milestone> task_milestone { get; set; }
        public virtual DbSet<tasks_completed> tasks_completed { get; set; }
        public virtual DbSet<title> titles { get; set; }
        public virtual DbSet<training_course> training_course { get; set; }
        public virtual DbSet<training_course_instance> training_course_instance { get; set; }
        public virtual DbSet<training_course_type> training_course_type { get; set; }
        public virtual DbSet<venue> venues { get; set; }
    
        public virtual ObjectResult<LoginEmail_Result> LoginEmail(ObjectParameter email, ObjectParameter passwords)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginEmail_Result>("LoginEmail", email, passwords);
        }
    }
}
