//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class task_milestone
    {
        [Display(Name = "Task Name")]
        public int Task_ID { get; set; }

        [Display(Name = "Milestone Name")]
        public int Milestone_ID { get; set; }

        [Required]
        [Display(Name = "Milestone Progress")]
        [Range(0, 1000, ErrorMessage = "Please enter a number that is above 0 but below 1000")]
        public int Task_Repetion { get; set; }
    
        public virtual milestone milestone { get; set; }
        public virtual task task { get; set; }
    }
}
