//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class training_course_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public training_course_type()
        {
            this.training_course = new HashSet<training_course>();
        }
    
        public int Training_Course_Type_ID { get; set; }

        [Required]
        [Display(Name = "Course Name")]
        [StringLength(50)]
        public string Course_Name { get; set; }

        [Required]
        [Display(Name = "Course Description")]
        [StringLength(255)]
        public string Course_Description { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<training_course> training_course { get; set; }
    }
}
