//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class venue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venue()
        {
            this.training_course_instance = new HashSet<training_course_instance>();
        }
    
        public int Venue_ID { get; set; }

        [Required]
        [Display(Name = "Venue Name")]
        [StringLength(50)]
        public string Venue_Name { get; set; }

        [Required]
        [Display(Name = "Venue Description")]
        [StringLength(255)]
        public string Venue_Description { get; set; }

        [Required]
        [Display(Name = "Venue Size")]
        [Range(5, 1000, ErrorMessage = "Please enter a number that is above 5 but below 1000")]
        public Nullable<int> Venue_Size { get; set; }

        [Required]
        [Display(Name = "Address")]
        public Nullable<int> Address_ID { get; set; }

        public virtual address address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<training_course_instance> training_course_instance { get; set; }
    }
}
